import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=' bg-gradient-to-b from-blue-400 to-blue-800 items-center justify-center h-full w-full bg-no-repeat'>{children}</body>
    </html>
  )
}
